### ISSUE TITLE
Observation Popup errors.

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-webmaps-public#18]
Clicking on some of observations in webmaps throws following type errors. 

```
popup.js:235 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at popup.js:235:20
    at tn.update (popup.js:186:7)
    at tn.render (index.js:56:54)
    at ue._handler (main.js:127:12)
    at ue._prerender (index.js:259:18)
    at Function.<anonymous> (index.js:157:24)
    at index.js:28:16
(anonymous) @ popup.js:235
tn.update @ popup.js:186
render @ index.js:56
(anonymous) @ main.js:127
ue._prerender @ index.js:259
(anonymous) @ index.js:157
(anonymous) @ index.js:28
requestAnimationFrame (async)
(anonymous) @ index.js:21
ee._emit @ index.js:160
emit @ index.js:26
(anonymous) @ main.js:107
t @ browser.js:2
t @ browser.js:2
h.l @ browser.js:2
entry66.a @ chunk.6d4ab7070c.js:sourcemap:1
u @ chunk.6d4ab7070c.js:sourcemap:1
o @ chunk.6d4ab7070c.js:sourcemap:1
(anonymous) @ chunk.6d4ab7070c.js:sourcemap:1

```

https://maps-public.mapeo.app/

**Comment by achou11** [comment]
todo: look into whether this is a runtime error related invalid data (e.g. a point missing an `x` value for its coordinate). thought we had addressed this issue but maybe there's some other area in the code that isn't handling this properly

**Comment by gmaclennan** [comment]
Thanks for sharing this Arky. Would you be able to share the dataset where this error is happening? I can load it via the dev version of webmaps and trace where this is coming from.
